### ISSUE TITLE
Invalid Redirect 

### ISSUE THREAD

**Issue by atbyrd** [lukedoolittle/quantfabric#118]
I'm trying to generate a user request url for fitbit. But whenever I visit the url generated I get the following error.

Developer information: invalid_request - Invalid redirect_uri parameter value 

### Source
        public async Task<HttpResponseMessage> Authorize(UserAuthRequestDTO request)
        {
            string authorizationUrl;
            switch (request.Manufacturer)
            {
                case "Fitbit":
                    var callbackUrl = !string.IsNullOrEmpty(request.CallbackUrl) ? request.CallbackUrl : $"http://localhost:49294/ouath2/callback"; //// &state={request.PatientID}";
                    var fitbit = new OAuth2Web<Material.Infrastructure.ProtectedResources.Fitbit>(
                        ConfigurationManager.AppSettings["FitbitConsumerKey"],
                        ConfigurationManager.AppSettings["FitbitConsumerSecret"],
                        callbackUrl)
                        .AddScope("activity")
                        .AddScope("heartrate")
                        .AddScope("profile")
                        .AddScope("sleep");
                    var fitbitUri = await fitbit.GetAuthorizationUriAsync(request.PatientID);
                    authorizationUrl = fitbitUri.AbsoluteUri;
                    break;
                case "Withings":
                    var withingsUri = await WithingsAuth1(request.PatientID).GetAuthorizationUriAsync(request.PatientID);
                    authorizationUrl = withingsUri.AbsoluteUri;
                    break;
                default:
                    return InvalidInputResponse();
            }
            return OkResponse(authorizationUrl);
        }

**Comment by lukedoolittle** [comment]
@atbyrd Just a guess but in the `callbackUrl` assignment line, you have `$"http://localhost:49294/ouath2/callback"` as the assigned string...did you misspell "oauth2" as "ouath2"? In OAuth2 workflow exchanges the callback url you pass has to match the url that you enter into the application portal EXACTLY otherwise the OAuth2 server will reject the request. That is what the `invalid_request - Invalid redirect_uri parameter value` error is indicating.

**Comment by atbyrd** [comment]
@lukedoolittle  Does the username param trick we did with withings work in OAuth2. I'm still getting the `Invalid redirect_uri paramater value`

### generated string

> https://www.fitbit.com/oauth2/authorize?client_id=22846N&scope=activity%20heartrate%20profile%20sleep&redirect_uri=http%3A%2F%2Flocalhost%3A49294%2Fapi%2Foauth2%2Fcallback%2Fpostman&response_type=code&state=hpgKEk8MoGa70JJAVpONKdEJCJPFWObf"

### callback url in code
`var callbackUrl = $"http://localhost:49294/api/oauth2/callback/{request.PatientID}";
`
### callback url on dev.fitbit.com
`http://localhost:49294/api/oauth2/callback/{username}
`

**Comment by lukedoolittle** [comment]
@atbyrd It doesn't work the same way with OAuth2 because in OAuth2 the redirect uri that you provide has to match EXACTLY the one you registered in the portal. So if `request.PatientID` is the same every time and the `{username}` as registered in the portal is hardcoded into your app then that will work. But that technique is quite inflexible.

The latest version I released at the end of last week (1.3.8) no longer requires a userId for either OAuth1 or OAuth2 calls, so both `GetAuthorizationUriAsync()` and `GetAccessTokenAsync()` have a parameter-less option. Otherwise the only option I know of, if you want to stick with the current version, is to use cookies.

**Comment by atbyrd** [comment]
@lukedoolittle It looks like the answer to my question is no, http://stackoverflow.com/questions/7722062/google-oauth2-redirect-uri-with-several-parameters. Can you add method to add a key/value to the state string. Maybe, AddToState("key", "value");
