### ISSUE TITLE
Fitbit Weight Data

### ISSUE THREAD

**Issue by antarr** [lukedoolittle/quantfabric#119]
I'm trying to get Weight Data from fitbit, but the authenticator does not include weight in the scope of the request url. The list of available scopes is [here](https://dev.fitbit.com/docs/oauth2/#scope).

**Comment by lukedoolittle** [comment]
I just realized this isn't covered in the wiki but you can add "custom" scopes to the request either through the request type itself or just as a string. You have to add them as a part of the `OAuth2Web` object before you get the authorization Uri from it. In your case what you would want is the following:

    OAuth2Web<Fitbit> oauth = new OAuth2Web<Fitbit>(
        clientId, 
        clientSecret, 
        callbackUri);

    Uri fitbitLoginEndpoint = await oauth
        .AddScope("weight")
        .GetAuthorizationUriAsync()
        .ConfigureAwait(false);

And I just realized after typing this that all of the Fitbit scopes weren't in the current build. So I updated the swagger document and published a new NuGet package 1.3.9. I haven't tested it because I don't have any Fitbit devices that utilize the "weight" scope but it should work.
